import { Button, Container } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'react-i18next';

const Scholar: NextPage = () => {
  const { t } = useTranslation();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container />
    </div>
  );
};

export default Scholar;
